# Telegram
telegram.gpb-bot.name: "GPB IT Factory Backend 2024"
telegram.gpb-bot.token: ${TELEGRAM_GPB_BOT_TOKEN}

# Datasource
spring.datasource.url: jdbc:postgresql://localhost:5432/gpb
spring.datasource.username: ${GPB_DB_USERNAME}
spring.datasource.password: ${GPB_DB_PASSWORD}
backend.base-url: "http://localhost:8080"
middle-service.base-url: "http://localhost:8080"

# FlyWay
spring.flyway.url: jdbc:postgresql://localhost:5432/gpb
spring.flyway.user: ${GPB_DB_USERNAME}
spring.flyway.password: ${GPB_DB_PASSWORD}
spring.flyway.locations: classpath:db/migration
